version: '3.1'

services:
  mongo:
    image: mongo
    container_name: zonaAzul
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: techChallenge
      MONGO_INITDB_ROOT_PASSWORD: fiap
      MONGO_INITDB_DATABASE: zonaAzulDB
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongoExpress
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: techChallenge
      ME_CONFIG_MONGODB_ADMINPASSWORD: fiap
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: techChallenge
      ME_CONFIG_BASICAUTH_PASSWORD: fiap
    ports:
      - 8081:8081

volumes:
  mongodata:
    driver: local
